<?xml version="1.0" encoding="utf-8"?>
<test-run id="2" name="Reflection.Randomness.exe" fullname="C:/MyRepo/Reflection.Randomness/Reflection.Randomness.csproj/bin/Debug/Reflection.Randomness.exe" testcasecount="8" result="Failed" start-time="2018-06-14 20:13:03Z" end-time="2018-06-14 20:13:04Z" duration="0.277524" total="8" passed="7" failed="1" inconclusive="0" skipped="0" asserts="13" random-seed="1238209600">
  <command-line><![CDATA["C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\bin\Debug\Reflection.Randomness.exe"   ]]></command-line>
  <filter />
  <test-suite type="Assembly" id="1009" name="Reflection.Randomness.exe" fullname="C:/MyRepo/Reflection.Randomness/Reflection.Randomness.csproj/bin/Debug/Reflection.Randomness.exe" runstate="Runnable" testcasecount="8" result="Failed" site="Child" start-time="2018-06-14 20:13:03Z" end-time="2018-06-14 20:13:04Z" duration="0.277524" total="8" passed="7" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="13">
    <environment framework-version="3.6.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\bin\Debug" machine-name="DESKTOP-MJHFLF4" user="altuk" user-domain="DESKTOP-MJHFLF4" culture="en-US" uiculture="en-US" os-architecture="x86" />
    <settings>
      <setting name="WorkDirectory" value="C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\bin\Debug" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="1944" />
      <property name="_APPDOMAIN" value="Reflection.Randomness.exe" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="1010" name="Reflection" fullname="Reflection" runstate="Runnable" testcasecount="8" result="Failed" site="Child" start-time="2018-06-14 20:13:03Z" end-time="2018-06-14 20:13:04Z" duration="0.245045" total="8" passed="7" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="13">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="1011" name="Randomness" fullname="Reflection.Randomness" runstate="Runnable" testcasecount="8" result="Failed" site="Child" start-time="2018-06-14 20:13:03Z" end-time="2018-06-14 20:13:04Z" duration="0.241834" total="8" passed="7" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="13">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestFixture" id="1000" name="Generator_should" fullname="Reflection.Randomness.Generator_should" classname="Reflection.Randomness.Generator_should" runstate="Runnable" testcasecount="8" result="Failed" site="Child" start-time="2018-06-14 20:13:03Z" end-time="2018-06-14 20:13:04Z" duration="0.230992" total="8" passed="7" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="13">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="1008" name="FailWithInformativeMessage_OnIncorrectAttributeUsage" fullname="Reflection.Randomness.Generator_should.FailWithInformativeMessage_OnIncorrectAttributeUsage" methodname="FailWithInformativeMessage_OnIncorrectAttributeUsage" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="187186051" result="Failed" start-time="2018-06-14 20:13:03Z" end-time="2018-06-14 20:13:03Z" duration="0.095724" asserts="1">
            <failure>
              <message><![CDATA[  Expected: <System.ArgumentException>
  But was:  <System.TypeInitializationException: The type initializer for 'Reflection.Randomness.Generator`1' threw an exception. ---> System.ArgumentException: Value does not fall within the expected range.
   at Reflection.Randomness.Generator`1..cctor() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator.cs:line 55
   --- End of inner exception stack trace ---
   at Reflection.Randomness.Generator`1..ctor() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator.cs:line 38
   at Reflection.Randomness.Generator_should.<>c.<FailWithInformativeMessage_OnIncorrectAttributeUsage>b__11_0() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator_should.cs:line 128
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>
]]></message>
              <stack-trace><![CDATA[at Reflection.Randomness.Generator_should.FailWithInformativeMessage_OnIncorrectAttributeUsage() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator_should.cs:line 128
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: <System.ArgumentException>
  But was:  <System.TypeInitializationException: The type initializer for 'Reflection.Randomness.Generator`1' threw an exception. ---> System.ArgumentException: Value does not fall within the expected range.
   at Reflection.Randomness.Generator`1..cctor() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator.cs:line 55
   --- End of inner exception stack trace ---
   at Reflection.Randomness.Generator`1..ctor() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator.cs:line 38
   at Reflection.Randomness.Generator_should.<>c.<FailWithInformativeMessage_OnIncorrectAttributeUsage>b__11_0() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator_should.cs:line 128
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>
]]></message>
                <stack-trace><![CDATA[at Reflection.Randomness.Generator_should.FailWithInformativeMessage_OnIncorrectAttributeUsage() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator_should.cs:line 128
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="1001" name="GenerateT1" fullname="Reflection.Randomness.Generator_should.GenerateT1" methodname="GenerateT1" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="1279526198" result="Passed" start-time="2018-06-14 20:13:04Z" end-time="2018-06-14 20:13:04Z" duration="0.036387" asserts="1" />
          <test-case id="1002" name="GenerateT1TwiceGivesUniqueObjects" fullname="Reflection.Randomness.Generator_should.GenerateT1TwiceGivesUniqueObjects" methodname="GenerateT1TwiceGivesUniqueObjects" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="809765712" result="Passed" start-time="2018-06-14 20:13:04Z" end-time="2018-06-14 20:13:04Z" duration="0.016154" asserts="1" />
          <test-case id="1003" name="GenerateT2" fullname="Reflection.Randomness.Generator_should.GenerateT2" methodname="GenerateT2" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="1167143211" result="Passed" start-time="2018-06-14 20:13:04Z" end-time="2018-06-14 20:13:04Z" duration="0.013243" asserts="4" />
          <test-case id="1004" name="NotAllowForAfterFor" fullname="Reflection.Randomness.Generator_should.NotAllowForAfterFor" methodname="NotAllowForAfterFor" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="590752961" result="Passed" start-time="2018-06-14 20:13:04Z" end-time="2018-06-14 20:13:04Z" duration="0.007625" asserts="1" />
          <test-case id="1005" name="ReplaceGeneratorFor1Field" fullname="Reflection.Randomness.Generator_should.ReplaceGeneratorFor1Field" methodname="ReplaceGeneratorFor1Field" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="176505347" result="Passed" start-time="2018-06-14 20:13:04Z" end-time="2018-06-14 20:13:04Z" duration="0.002911" asserts="2" />
          <test-case id="1006" name="ReplaceGeneratorFor2Fields" fullname="Reflection.Randomness.Generator_should.ReplaceGeneratorFor2Fields" methodname="ReplaceGeneratorFor2Fields" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="1850204719" result="Passed" start-time="2018-06-14 20:13:04Z" end-time="2018-06-14 20:13:04Z" duration="0.002361" asserts="2" />
          <test-case id="1007" name="SetGeneratorForFieldWithoutAttributes" fullname="Reflection.Randomness.Generator_should.SetGeneratorForFieldWithoutAttributes" methodname="SetGeneratorForFieldWithoutAttributes" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="848330174" result="Passed" start-time="2018-06-14 20:13:04Z" end-time="2018-06-14 20:13:04Z" duration="0.001922" asserts="1" />
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>